### ISSUE TITLE
Please invite me to the community

### ISSUE THREAD

**Issue by nirbhaybiotech** [cac-nitj/support#28]
### Name

Nirbhay Kumar

### Additional Context

Doing workshop and spreading the knowledge and valuable time to peers to grow and carve theirselves into tech field.

**Comment by nirbhaybiotech** [comment]
Is this receive?

**Comment by nirbhaybiotech** [comment]
Is this receive?

**Comment by KukretiShubham** [comment]
yes you are part of organization now :)
